### ISSUE TITLE
Usage of Events

### ISSUE THREAD

**Issue by arohr** [arjanverstoep/sach-modellierung#2]
What is the status about the usage of events? In my understanding we have decided not to use events (meeting 17.4.2015). The idea of AWK was to optimize the access to data using events, because they were afraid regular data subscriptions could overload the system. In my opinion this is not true (the subscription mechanism is highly optimized), so the usage of events for this purpose make no sense.

In addition, I don't understand the objects like "E_Ch_F" (NodeId ns=1;i=5012), which I believe this is wrong. Events in OPC UA are not visible as nodes in the Address Space. Thus, the component "E_Ch_F" of "DeviceType" makes no sense to me...

**Comment by arjanverstoep** [comment]
The latest specifications from AWK still mention events like the CommunicationFailureEventType for the DeviceType's Status/ComState variable. I have defined the E_Ch_F object below the DeviceType as an OptionalPlaceholder to put the information into the model that such an EventType can be published for this typical. Otherwise, the information in the .ua-file would be incomplete, and the server that initializes its address space by using the exported XML cannot know that such events should be generated.

**Comment by arohr** [comment]
The information that _ControllerType/Status/ComState_ can generate a _CommunicationFailureEventType_ must be modeled by adding a _GeneratesEvent_ Reference from _ControllerType_ to _CommunicationFailureEventType_ and a _HasEventSource_ Reference from _ControllerType_ to _ControllerType/Status/ComState_ as far as I know.

Do you expect my AS NT to send such events?

**Comment by arjanverstoep** [comment]
Mmmkay, that makes a lot of sense.

My client is not interested in events.

**Comment by arohr** [comment]
OK, I will not implement any events. Thus, the attribute _EventNotifier_ of every instance Object-node will be _None_.

In my opinion all events should be removed from the SA-CH spec, or at least correctly modelled...
